# /etc/ssh/sshd_config.d/20-example.conf
# Everything is first-match-wins.
# If it doesn't work, check upstream configs.
# Be careful with Match blocks; don't treat it like a programming if-else.
# First-match-wins still holds with Match statements too.

Port 5xxxx
PermitRootLogin no
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey

# AllowUsers/DenyUsers/AllowGroups: All occurances combine into a single master policy.
# User 'hoge' can access from 10.xx.yy.0/24 or 172.30.zz.0/24
AllowUsers hoge@10.xx.yy.0/24 hoge@172.30.zz.0/24
# Users alice and bob can login from any address, user admin can only access from 192.168.1.50
AllowUsers alice bob admin@192.168.1.50
# All other users and source IPs are implicitly denied.

MaxAuthTries 3
MaxSessions 2
X11Forwarding no
AllowAgentForwarding no
AllowStreamLocalForwarding no
PermitRemoteForwarding no
ClientAliveInterval 300
ClientAliveCountMax 2

Match User hoge Address 10.xx.yy.0.0/24, 172.30.zz.0/24
    AllowTcpForwarding yes
    PermitLocalForwarding yes

# Match All terminates the Match block above. Don't think of it as an if-else.
# Without it, everything under will still be part of the above match condition block.
Match All
    MaxStartups 10:30:100
    AllowTcpForwarding no
    PermitLocalForwarding no
