# /etc/ssh/sshd_config.d/20-example.conf

# The config is read 2 times.
# 1. When the SSH server deamon starts up; sshd reads all the config and loads the defaults.
# 2. When a client tries to connect; sshd evaluates the Match block and overrules when it finds a match.
# Match always wins, everything not in Match block is First-Match-Wins/Append (see below).
# Be careful with Match blocks; don't treat it like a programming if-else.

# Scalar vs List values.
# Scalar Values: first-match-wins
# - PermitRootLogin
# - Port
# - AllowTcpForwarding
# - etc.
# List Values: append-to-list
# - AllowUsers
# - DenyUsers
# - AllowGroups
# - AcceptEnv
# - AuthenticationMethods 

Port 5xxxx
PermitRootLogin no
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey

MaxAuthTries 3
MaxSessions 2
X11Forwarding no
AllowAgentForwarding no
AllowStreamLocalForwarding no
ClientAliveInterval 300
ClientAliveCountMax 2

# User 'hoge' can access from 10.xx.yy.0/24 or 172.30.zz.0/24
AllowUsers hoge@10.xx.yy.0/24 hoge@172.30.zz.0/24
# Users alice and bob can login from any address, user admin can only access from 192.168.1.50
AllowUsers alice bob admin@192.168.1.50
# All other users and source IPs are implicitly denied.

Match User hoge Address 10.xx.yy.0.0/24,172.30.zz.0/24
    AllowTcpForwarding yes
# Match All terminates the Match block above. Don't think of it as an if-else.
# Match All includes all; including hoge in the above Match block.
# Without it, everything under will still be part of the above match condition block.
Match All
